image: docker:latest

stages:
  - build
  - deploy

.gcp:
  image: google/cloud-sdk
  services:
    - docker:dind
  script:
    #- gcloud auth activate-service-account --key-file <(echo -n "${GCP_SERVICEACCOUNT_KEY}" | base64 -d )
    - gcloud auth activate-service-account --key-file $GCP_SERVICEACCOUNT_KEYFILE
    - cd quarkus-workshop-super-heroes/super-heroes/rest-villain/
    - deployment/gcp/cloudbuild-$CI_JOB_STAGE.sh
  variables:
    TERRAFORM_ENVIRONMENT: $CI_COMMIT_BRANCH
    IMAGE_TAG: $CI_COMMIT_SHA

build:
  stage: build
  extends:
    - .gcp
  rules:
    - if: $TARGET == "build" || $TARGET == ""

deploy:
  stage: deploy
  extends:
    - .gcp
  rules:
    - if: $TARGET == "deploy" || $TARGET == ""
