# Run gitlab-env.sh to print variables required in GitLab CI.

# This GitLab CI pipeline triggers Google Cloud Build on changes:
# - Provisioning of infrastructure
# - Building of services
# - Deployment of services
#
# Triggering the builds is required because the GitLab repository is not available on the Internet
# so that we cannot add triggers to Google Cloud Build.
#
# The actual workflow steps should be implemented in scripts to avoid a strong dependency on Google Cloud Build.

image: alpine

stages:
  - one
  - two


infrastructure:
  stage: one
  trigger:
    include: /quarkus-workshop-super-heroes/infrastructure/.gitlab-ci.yml
    strategy: depend
  only:
    refs:
      - branches
    changes:
      - /quarkus-workshop-super-heroes/infrastructure/


build villain service:
  stage: one
  trigger:
    include: /quarkus-workshop-super-heroes/super-heroes/rest-villain/deployment/gcp/.gitlab-ci.yml
    strategy: depend
  variables:
    TARGET: build
  only:
    refs:
      - branches
    changes:
      - /quarkus-workshop-super-heroes/super-heroes/rest-villain/


deploy villain service:
  stage: two
  needs:
    - build villain service
    - infrastructure
  trigger:
    include: /quarkus-workshop-super-heroes/super-heroes/rest-villain/deployment/gcp/.gitlab-ci.yml
    strategy: depend
  variables:
    TARGET: deploy
  only:
    refs:
      - branches
    changes:
      - /quarkus-workshop-super-heroes/super-heroes/rest-villain/
      - /quarkus-workshop-super-heroes/infrastructure/


# https://docs.gitlab.com/ee/ci/environments

#  script:
#    - DYNAMIC_ENVIRONMENT_URL=$(deploy-script)                                 # In script, get the environment URL.
#    - echo "DYNAMIC_ENVIRONMENT_URL=$DYNAMIC_ENVIRONMENT_URL" >> deploy.env    # Add the value to a dotenv file.
#  artifacts:
#    reports:
#      dotenv: deploy.env                                                       # Report back dotenv file to rails.
#  environment:
#    name: review/$CI_COMMIT_REF_SLUG
#    url: $DYNAMIC_ENVIRONMENT_URL                                              # and set the variable produced in script to `environment:url`
#    on_stop: stop_review
#
