# Run gitlab-env.sh to print variables required in GitLab CI.

stages:
  - infrastructure_provision
  - services_build
  - services_deploy


terraform_apply:
  stage: infrastructure_provision
  trigger:
    include:
      - file: terraform/.gitlab-ci.yml
  only:
    refs:
      - branches
    changes:
      - infrastructure/


service_villain_build:
  stage: services_build
  trigger:
    include:
      - file: super-heroes/rest-villain/.gitlab-ci.yml
  variables:
    - STAGE: build
  only:
    refs:
      - branches
    changes:
      - super-heroes/rest-villain/


service_villain_deploy:
  stage: services_deploy
  needs: [infrastructure_deploy,service_villain_build]
  trigger:
    include:
      - file: super-heroes/rest-villain/.gitlab-ci.yml
  variables:
    - STAGE: deploy
  only:
    refs:
      - branches
    changes:
      - super-heroes/rest-villain/
      - infrastructure/


# https://docs.gitlab.com/ee/ci/environments

#  script:
#    - DYNAMIC_ENVIRONMENT_URL=$(deploy-script)                                 # In script, get the environment URL.
#    - echo "DYNAMIC_ENVIRONMENT_URL=$DYNAMIC_ENVIRONMENT_URL" >> deploy.env    # Add the value to a dotenv file.
#  artifacts:
#    reports:
#      dotenv: deploy.env                                                       # Report back dotenv file to rails.
#  environment:
#    name: review/$CI_COMMIT_REF_SLUG
#    url: $DYNAMIC_ENVIRONMENT_URL                                              # and set the variable produced in script to `environment:url`
#    on_stop: stop_review
#
