image: docker:latest

terraform:
  image: google/cloud-sdk
  services:
    - docker:dind
  script:
    - pwd
    - find . -type d
    #- gcloud auth activate-service-account --key-file <(echo -n "${GCP_SERVICEACCOUNT_KEY}" | base64 -d )
    - gcloud auth activate-service-account --key-file $GCP_SERVICEACCOUNT_KEYFILE
    - ./cloudbuild.sh
