image: docker:latest

terraform:
  image: google/cloud-sdk:slim
  services:
    - docker:dind
  script:
    #- gcloud auth activate-service-account --key-file <(echo -n "${GCP_SERVICEACCOUNT_KEY}" | base64 -d )
    - gcloud auth activate-service-account --key-file $GCP_SERVICEACCOUNT_KEYFILE
    - cd quarkus-workshop-super-heroes/infrastructure/
    - ./cloudbuild.sh
