image: docker:latest

stages:
  - provision

terraform:
  stage: provision
  image: google/cloud-sdk:slim
  services:
    - docker:dind
  script:
    #- gcloud auth activate-service-account --key-file <(echo -n "${GCP_SERVICEACCOUNT_KEY}" | base64 -d )
    - gcloud auth activate-service-account --key-file $GCP_SERVICEACCOUNT_KEYFILE
    - cd quarkus-workshop-super-heroes/infrastructure/
    - ./cloudbuild.sh
  variables:
    TERRAFORM_ENVIRONMENT: $CI_COMMIT_BRANCH
  rules:
    - if: $GCP_PROJECT_ID
  environment:
    name: $CI_COMMIT_BRANCH
