[[section-design-decisions]]
== Design Decisions


[role="arc42help"]
****
.Contents
Important, expensive, large scale or risky architecture decisions including rationals.
With "decisions" we mean selecting one alternative based on given criteria.

Please use your judgement to decide whether an architectural decision should be documented
here in this central section or whether you better document it locally
(e.g. within the white box template of one building block).

Avoid redundancy. Refer to section 4, where you already captured the most important decisions of your architecture.

.Motivation
Stakeholders of your system should be able to comprehend and retrace your decisions.

.Form
Various options:

* List or table, ordered by importance and consequences or:
* more detailed in form of separate sections per decision
* ADR (architecture decision record) for every important decision
****



Stichpunkte in Meeting Minutes!


Cloud Build für parallele Nutzung mehrerer Container mit viel RAM und CPU für Erzeugung von native binaries.

The actual workflow steps should be implemented in scripts to avoid a strong dependency on Google Cloud Build.

Triggering the builds is required because the GitLab repository is not available on the Internet
so that we cannot add triggers to Google Cloud Build.


Mono Repo

Single Infrastructure configuration
Uniform Infrastructure configuration


Keine Serverless-Datenbank, weil nicht kompatibel zu etwas, das man selbst hosten kann

Keine Functions, weil bei Cloud Anbietern nicht kompatibel zu etwas, das man selbst hosten kann


Microservices, weil ...

MongoDB, weil ....

Apache Kafka, weil ...
