[[section-glossary]]
== Glossary

[role="arc42help"]
****
.Contents
The most important domain and technical terms that your stakeholders use when discussing the system.

You can also see the glossary as source for translations if you work in multi-language teams.

.Motivation
You should clearly define your terms, so that all stakeholders

* have an identical understanding of these terms
* do not use synonyms and homonyms

.Form
* A table with columns <Term> and <Definition>.
* Potentially more columns in case you need translations.
****

Continuous Integration (CI)[[glossary-continuous-integration]]:: In software engineering, continuous integration (CI) is the practice of merging all developers' working copies to a shared mainline several times a day. Grady Booch first proposed the term CI in his 1991 method, although he did not advocate integrating several times a day.
https://en.wikipedia.org/wiki/Continuous_integration[Source^]

Continuous Delivery (CD)[[glossary-continuous-delivery]]:: Continuous delivery (CD) is a software engineering approach in which teams produce software in short cycles, ensuring that the software can be reliably released at any time and, when releasing the software, without doing so manually.[1][2] It aims at building, testing, and releasing software with greater speed and frequency. The approach helps reduce the cost, time, and risk of delivering changes by allowing for more incremental updates to applications in production. A straightforward and repeatable deployment process is important for continuous delivery
https://en.wikipedia.org/wiki/Continuous_delivery[Source^]

Continuous Deployment (CD)[[glossary-continuous-deployment]]:: Continuous deployment (CD) is a software engineering approach in which software functionalities are delivered frequently through automated deployments. CD contrasts with continuous delivery, a similar approach in which software functionalities are also frequently delivered and deemed to be potentially capable of being deployed but are actually not deployed. +
{empty} +
In an environment in which data-centric microservices provide the functionality, and where the microservices can have multiple instances, CD consists of instantiating the new version of a microservice and retiring the old version as it has drained all the requests in flight.
https://en.wikipedia.org/wiki/Continuous_deployment[Source^]

Infrastructure as Code (IaC)[[glossary-iac]]:: Infrastructure as code (IaC) is the process of managing and provisioning computer data centers through machine-readable definition files, rather than physical hardware configuration or interactive configuration tools. +
{empty} +
The IT infrastructure managed by this process comprises both physical equipment, such as bare-metal servers, as well as virtual machines, and associated configuration resources. The definitions may be in a version control system. +
{empty} +
It can use either scripts or declarative definitions, rather than manual processes, but the term is more often used to promote declarative approaches.
https://en.wikipedia.org/wiki/Infrastructure_as_code[Source^]

Terraform[[glossary-terraform]]:: https://www.terraform.io/[Terraform^] is an IaC tool for building, changing, and versioning infrastructure. Terraform can manage service providers as well as custom in-house solutions. +
{empty} +
Configuration files describe to Terraform the components needed to run an application. Terraform generates an execution plan describing what it will do to reach the desired state, and then executes it to build the described infrastructure. As the configuration changes, Terraform is able to determine what changed and create incremental execution plans which can be applied. +
{empty} +
The infrastructure Terraform can manage includes low-level components such as compute instances, storage, and networking, as well as high-level components such as DNS entries, SaaS features, etc. https://www.terraform.io/intro/index.html[Source^]

GitOps[[glossary-gitops]]:: GitOps is an operational framework that takes DevOps best practices used for application development such as version control, collaboration, compliance, and CI/CD, and applies them to infrastructure automation. +
{empty} +
GitOps is used to automate the process of provisioning infrastructure. Similar to how teams use application source code, operations teams that adopt GitOps use configuration files stored as code (infrastructure as code). GitOps configuration files generate the same infrastructure environment every time it is deployed, just as application source code generates the same application binaries every time it is built. +
{empty} +
GitOps uses a Git repository as the single source of truth for infrastructure definitions.
https://about.gitlab.com/topics/gitops/[Source^]



Git[[glossary-git]]::

GitLab[[glossary-gitlab]]::

GitLab CI[[glossary-gitlab-ci]]::


Container[[glossary-container]]::

Knative[[glossary-knative]]::

Kubernetes[[glossary-kubernetes]]::

Serverless[[glossary-serverless]]::
