version: '2'
services:

  rest-hero:
    #container_name: "quarkus-workshop-rest-hero"
    image: "tbuehren/quarkus-workshop-rest-hero"
    ports:
      - 8083:8080
    network_mode: "host"

  rest-villain:
    #container_name: "quarkus-workshop-rest-villain"
    image: "tbuehren/quarkus-workshop-rest-villain"
    ports:
      - 8084:8080
    network_mode: "host"

  rest-fight:
    #container_name: "quarkus-workshop-rest-fight"
    image: "tbuehren/quarkus-workshop-rest-fight"
    ports:
      - 8082:8080
    network_mode: "host"

  event-statistics:
    #container_name: "quarkus-workshop-event-statistics"
    image: "tbuehren/quarkus-workshop-event-statistics"
    ports:
      - 8085:8080
    network_mode: "host"
