steps:
- name: 'gcr.io/kaniko-project/executor:latest'
  args:
    - --destination=eu.gcr.io/$_GCLOUD_PROJECT_ID/$_SERVICE
    - --cache=true
    - --cache-ttl=120h
    - --build-arg=MAVEN_EXTRA_ARGS=$_MAVEN_EXTRA_ARGS
    - --build-arg=QUARKUS_PROFILE=$_QUARKUS_PROFILE
options:
  machineType: 'E2_HIGHCPU_32'

#steps:
#- name: 'gcr.io/cloud-builders/docker'
#  args: [
#    'build',
#    '-t', 'gcr.io/$_GCLOUD_PROJECT_ID/$_SERVICE',
#    '--build-arg', 'MAVEN_EXTRA_ARGS=$_MAVEN_EXTRA_ARGS',
#    '--build-arg', 'QUARKUS_PROFILE=$_QUARKUS_PROFILE',
#    '.'
#]
#options:
#  machineType: 'E2_HIGHCPU_8'
#images:
#- 'gcr.io/$_GCLOUD_PROJECT_ID/$_SERVICE'
