# Deploy service to Google Cloud Run.
# Image must be built and pushed to Google Container Registry before.

steps:

# Deploy container image to Cloud Run
# https://cloud.google.com/build/docs/deploying-builds/deploy-cloud-run#gcloud
# - envsubst replaces placeholders in the yaml files with environment variables.
# - berglas fetches secrets for environment variables "sm://$PROJECT_ID/..." from GCP Secret Manager
- id: deploy
  name: 'eu.gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
  #name: 'gcr.io/cloud-builders/gcloud-slim' How to install envsubst here?
  entrypoint: 'bash' # https://cloud.google.com/build/docs/configuring-builds/run-bash-scripts
  args:
    - '-eEuo'
    - 'pipefail'
    - '-c'
    - |-
      echo "_SERVICE=${_SERVICE}"
      echo ""
      echo "PROJECT_ID=${PROJECT_ID}"
      echo "BRANCH_NAME=${BRANCH_NAME} (Terraform environment)"
      echo "COMMIT_SHA=${COMMIT_SHA} (Image Tag)"
      echo ""
      echo "_KNATIVE_SERVICE_FILE=${_KNATIVE_SERVICE_FILE}"
      echo "_POLICY_FILE=${_POLICY_FILE}"
      echo ""
      echo "_QUARKUS_PROFILE=${_QUARKUS_PROFILE}"

      IMAGE="eu.gcr.io/${PROJECT_ID}/${_SERVICE}:${COMMIT_SHA}"
      echo "IMAGE=$${IMAGE}"

      deployment/gcp/cloudrun-deploy.sh "${PROJECT_ID}" "${BRANCH_NAME}" "${_SERVICE}" "$${IMAGE}" "${_KNATIVE_SERVICE_FILE}" "${_POLICY_FILE}" "${_QUARKUS_PROFILE}"


substitutions:
  _SERVICE: "undefined" # define as substitution
  _KNATIVE_SERVICE_FILE: "deployment/knative/service.yaml" # default value
  _POLICY_FILE: "deployment/gcp/policy.yaml" # default value
  _QUARKUS_PROFILE: "googlecloud" # default value
