image: docker:latest

stages:
  - build
  - deploy


.gcp-base:
  image: google/cloud-sdk:slim
  services:
    - docker:dind
  variables:
    TERRAFORM_ENVIRONMENT: $CI_COMMIT_BRANCH
    IMAGE_TAG: $CI_COMMIT_SHA
  before_script:
    - echo "$CI_JOB_STAGE $SERVICE_NAME"
    #- gcloud auth activate-service-account --key-file <(echo -n "${GCP_SERVICEACCOUNT_KEY}" | base64 -d )
    - gcloud auth activate-service-account --key-file $GCP_SERVICEACCOUNT_KEYFILE
    - cd $SERVICE_DIR/
  script:
    - deployment/gcp/cloudbuild-$CI_JOB_STAGE.sh
  environment:
    name: $CI_COMMIT_BRANCH
    action: prepare # allows running multiple jobs in parallel for the same environment
  only:
    variables:
      - $GCP_PROJECT_ID
      - $GCP_SERVICEACCOUNT_KEYFILE
      - $GCP_BUCKET_CLOUDBUILD_LOG
      - $GCP_BUCKET_CLOUDBUILD_SOURCE
      - $GCP_REGION


build service:
  stage: build
  extends:
    - .gcp-base
  only:
    variables:
      - $TARGET == "build" || $TARGET == ""


deploy service:
  stage: deploy
  extends:
    - .gcp-base
  only:
    variables:
      - $TARGET == "deploy" || $TARGET == ""
